package reports.management;

import org.apache.pdfbox.pdmodel.PDDocument;
import org.apache.pdfbox.pdmodel.PDPage;
import org.apache.pdfbox.pdmodel.PDPageContentStream;
import org.apache.pdfbox.pdmodel.common.PDRectangle;
import org.apache.pdfbox.pdmodel.font.PDType1Font;
import org.apache.pdfbox.pdmodel.font.Standard14Fonts;

import java.io.File;
import java.io.IOException;
import java.sql.*;

public class GeneratePDF {
    public static void generateStockSummary(String from_date, String to_date, int reportId, String generatedBy, String dateAndTime) {
        String sql = "SELECT * FROM fish_stock WHERE catch_date BETWEEN ? AND ?";
        String outputPath = "C:/Users/ADITHYA/Desktop/Fish Stock Summary.pdf";

        try (
                Connection connection = DriverManager.getConnection(
                        "jdbc:mysql://localhost:3306/oceanops", "root", "adithya123"
                );
                PreparedStatement statement = connection.prepareStatement(
                        sql,
                        ResultSet.TYPE_SCROLL_INSENSITIVE,
                        ResultSet.CONCUR_READ_ONLY
                )
        ) {
            Class.forName("com.mysql.cj.jdbc.Driver");

            statement.setString(1, from_date);
            statement.setString(2, to_date);
            ResultSet rs = statement.executeQuery();

            PDDocument document = new PDDocument();
            PDPage page = new PDPage();
            document.addPage(page);

            float margin = 50;
            float y = 750;
            float rowHeight = 30;
            float[] colWidths = {100, 100, 100, 150};
            float tableWidth = 0;
            for (float w : colWidths) tableWidth += w;

            // Header
            PDPageContentStream headerStream = new PDPageContentStream(document, page);
            headerStream.setFont(new PDType1Font(Standard14Fonts.FontName.HELVETICA_BOLD), 14);
            headerStream.beginText();
            headerStream.newLineAtOffset(margin, y);
            headerStream.showText("Fish Stock Summary");
            headerStream.endText();

            y -= 30;

            headerStream.setFont(new PDType1Font(Standard14Fonts.FontName.HELVETICA), 12);
            headerStream.beginText();
            headerStream.newLineAtOffset(margin, y);
            headerStream.showText("Report ID: R" + String.format("%04d", reportId));
            headerStream.newLineAtOffset(0, -20);
            headerStream.showText("Report Date: " + dateAndTime);
            headerStream.newLineAtOffset(0, -20);
            headerStream.showText("Generated By: " + generatedBy);
            headerStream.newLineAtOffset(0, -20);
            headerStream.showText("Date Range: " + from_date + " to " + to_date);
            headerStream.newLineAtOffset(0, -20);
            headerStream.showText("Stock Unloaded Date:");
            headerStream.endText();
            headerStream.close();

            y -= 130;

            // Read data and prepare table
            rs.last();
            int rowCount = rs.getRow();
            rs.beforeFirst();

            String[][] tableData = new String[rowCount + 2][4]; // +1 header, +1 total
            double totalQuantity = 0;

            tableData[0] = new String[]{"Boat ID", "Fish Type", "Quantity", "Catch Date"};

            int index = 1;
            while (rs.next()) {
                String boatId = rs.getString("boat_id");
                String fishType = rs.getString("fish_type_id");
                String quantity = rs.getString("quantity_kg");
                String catchDate = rs.getString("catch_date");

                totalQuantity += Double.parseDouble(quantity);

                tableData[index++] = new String[]{
                        boatId,
                        fishType,
                        String.format("%.2f", Double.parseDouble(quantity)),
                        catchDate
                };
            }

            tableData[index] = new String[]{"", "Total", String.format("%.2f", totalQuantity), ""};

            // Draw table
            PDPageContentStream tableStream = new PDPageContentStream(document, page, PDPageContentStream.AppendMode.APPEND, true);

            for (int i = 0; i < tableData.length; i++) {
                if (y - rowHeight < 100) {
                    tableStream.close();
                    page = new PDPage();
                    document.addPage(page);
                    y = 750;
                    tableStream = new PDPageContentStream(document, page);
                }

                float x = margin;
                for (int j = 0; j < tableData[i].length; j++) {
                    tableStream.beginText();
                    PDType1Font font = (i == 0 || i == tableData.length - 1)
                            ? new PDType1Font(Standard14Fonts.FontName.HELVETICA_BOLD)
                            : new PDType1Font(Standard14Fonts.FontName.HELVETICA);
                    tableStream.setFont(font, 12);
                    tableStream.newLineAtOffset(x + 5, y - 20);
                    tableStream.showText(tableData[i][j] == null ? "" : tableData[i][j]);
                    tableStream.endText();
                    x += colWidths[j];
                }

                tableStream.moveTo(margin, y - rowHeight);
                tableStream.lineTo(margin + tableWidth, y - rowHeight);
                tableStream.stroke();

                y -= rowHeight;
            }

            // Footer section
            y -= 70;
            PDRectangle box = page.getMediaBox();
            float pageWidth = box.getWidth();
            float leftX = margin;
            float rightX = pageWidth - margin - 150;

            tableStream.setLineDashPattern(new float[]{3}, 0);

            tableStream.moveTo(leftX, y);
            tableStream.lineTo(leftX + 150, y);
            tableStream.stroke();

            tableStream.moveTo(rightX, y);
            tableStream.lineTo(rightX + 150, y);
            tableStream.stroke();

            tableStream.setLineDashPattern(new float[]{}, 0);

            PDType1Font footerFont = new PDType1Font(Standard14Fonts.FontName.HELVETICA);
            float fontSize = 12;
            float offsetY = 15;

            String leftText = "Report Date";
            float leftWidth = footerFont.getStringWidth(leftText) / 1000 * fontSize;
            float leftTextX = leftX + (150 - leftWidth) / 2;

            tableStream.beginText();
            tableStream.setFont(footerFont, fontSize);
            tableStream.newLineAtOffset(leftTextX, y - offsetY);
            tableStream.showText(leftText);
            tableStream.endText();

            String rightText = "Authorized By";
            float rightWidth = footerFont.getStringWidth(rightText) / 1000 * fontSize;
            float rightTextX = rightX + (150 - rightWidth) / 2;

            tableStream.beginText();
            tableStream.setFont(footerFont, fontSize);
            tableStream.newLineAtOffset(rightTextX, y - offsetY);
            tableStream.showText(rightText);
            tableStream.endText();

            tableStream.close(); // ✅ very important
            document.save(new File(outputPath));
            document.close();

            System.out.println("PDF file generated successfully at: " + outputPath);

        } catch (IOException | SQLException | ClassNotFoundException e) {
            e.printStackTrace();
        }
    }

    public static void generateComplianceSummary(String from_date, String to_date, int reportId, String generatedBy, String dateAndTime) {

        String sql = "SELECT * FROM compliance WHERE violation_date BETWEEN ? AND ?";
        String outputPath = "C:/Users/ADITHYA/Desktop/Compliance Summary.pdf";

        try (
                Connection connection = DriverManager.getConnection(
                        "jdbc:mysql://localhost:3306/oceanops", "root", "adithya123"
                );
                PreparedStatement statement = connection.prepareStatement(
                        sql,
                        ResultSet.TYPE_SCROLL_INSENSITIVE,
                        ResultSet.CONCUR_READ_ONLY
                )
        ) {
            Class.forName("com.mysql.cj.jdbc.Driver");

            statement.setString(1, from_date);
            statement.setString(2, to_date);
            ResultSet rs = statement.executeQuery();

            PDDocument document = new PDDocument();
            PDPage page = new PDPage();
            document.addPage(page);

            float margin = 50;
            float y = 750;
            float rowHeight = 30;
            float[] colWidths = {80, 80, 140, 120, 100}; // 5 columns
            float tableWidth = 0;
            for (float w : colWidths) tableWidth += w;

            // Header
            PDPageContentStream headerStream = new PDPageContentStream(document, page);
            headerStream.setFont(new PDType1Font(Standard14Fonts.FontName.HELVETICA_BOLD), 14);
            headerStream.beginText();
            headerStream.newLineAtOffset(margin, y);
            headerStream.showText("Compliance Summary Report");
            headerStream.endText();

            y -= 30;

            headerStream.setFont(new PDType1Font(Standard14Fonts.FontName.HELVETICA), 12);
            headerStream.beginText();
            headerStream.newLineAtOffset(margin, y);
            headerStream.showText("Report ID: R" + String.format("%04d", reportId));
            headerStream.newLineAtOffset(0, -20);
            headerStream.showText("Report Date: " + dateAndTime);
            headerStream.newLineAtOffset(0, -20);
            headerStream.showText("Generated By: " + generatedBy);
            headerStream.newLineAtOffset(0, -20);
            headerStream.showText("Date Range: " + from_date + " to " + to_date);
            headerStream.newLineAtOffset(0, -20);
            headerStream.showText("Stock Unloaded Date:");
            headerStream.endText();
            headerStream.close();

            y -= 130;

            // Prepare table
            rs.last();
            int rowCount = rs.getRow();
            rs.beforeFirst();

            String[][] tableData = new String[rowCount + 1][5]; // no total row for compliance
            tableData[0] = new String[]{"Notice ID", "Boat ID", "Violation", "Violation Date", "Status"};

            int index = 1;
            while (rs.next()) {
                tableData[index++] = new String[]{
                        rs.getString("notice_id"),
                        rs.getString("boat_id"),
                        rs.getString("violation"),
                        rs.getString("violation_date"),
                        rs.getString("status")
                };
            }

            // Draw table
            PDPageContentStream tableStream = new PDPageContentStream(document, page, PDPageContentStream.AppendMode.APPEND, true);

            for (int i = 0; i < tableData.length; i++) {
                if (y - rowHeight < 100) {
                    tableStream.close();
                    page = new PDPage();
                    document.addPage(page);
                    y = 750;
                    tableStream = new PDPageContentStream(document, page);
                }

                float x = margin;
                for (int j = 0; j < tableData[i].length; j++) {
                    tableStream.beginText();
                    PDType1Font font = (i == 0)
                            ? new PDType1Font(Standard14Fonts.FontName.HELVETICA_BOLD)
                            : new PDType1Font(Standard14Fonts.FontName.HELVETICA);
                    tableStream.setFont(font, 12);
                    tableStream.newLineAtOffset(x + 5, y - 20);
                    tableStream.showText(tableData[i][j] == null ? "" : tableData[i][j]);
                    tableStream.endText();
                    x += colWidths[j];
                }

                tableStream.moveTo(margin, y - rowHeight);
                tableStream.lineTo(margin + tableWidth, y - rowHeight);
                tableStream.stroke();

                y -= rowHeight;
            }

            // Footer
            y -= 70;
            PDRectangle box = page.getMediaBox();
            float pageWidth = box.getWidth();
            float leftX = margin;
            float rightX = pageWidth - margin - 150;

            tableStream.setLineDashPattern(new float[]{3}, 0);

            tableStream.moveTo(leftX, y);
            tableStream.lineTo(leftX + 150, y);
            tableStream.stroke();

            tableStream.moveTo(rightX, y);
            tableStream.lineTo(rightX + 150, y);
            tableStream.stroke();

            tableStream.setLineDashPattern(new float[]{}, 0);

            PDType1Font footerFont = new PDType1Font(Standard14Fonts.FontName.HELVETICA);
            float fontSize = 12;
            float offsetY = 15;

            String leftText = "Report Date";
            float leftWidth = footerFont.getStringWidth(leftText) / 1000 * fontSize;
            float leftTextX = leftX + (150 - leftWidth) / 2;

            tableStream.beginText();
            tableStream.setFont(footerFont, fontSize);
            tableStream.newLineAtOffset(leftTextX, y - offsetY);
            tableStream.showText(leftText);
            tableStream.endText();

            String rightText = "Authorized By";
            float rightWidth = footerFont.getStringWidth(rightText) / 1000 * fontSize;
            float rightTextX = rightX + (150 - rightWidth) / 2;

            tableStream.beginText();
            tableStream.setFont(footerFont, fontSize);
            tableStream.newLineAtOffset(rightTextX, y - offsetY);
            tableStream.showText(rightText);
            tableStream.endText();

            tableStream.close();
            document.save(new File(outputPath));
            document.close();

            System.out.println("PDF file generated successfully at: " + outputPath);

        } catch (IOException | SQLException | ClassNotFoundException e) {
            e.printStackTrace();
        }
    }
}
